name: Generate isometric contributions metrics

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: vitorsilvestre29
          template: classic
          base: ""
          filename: metrics.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          output_action: commit
          committer_branch: output
          committer_message: "chore: update metrics [Skip GitHub Action]"
          optimize: xml
          extras_css: |
            svg { background-color: #0d1117 !important; }
            svg { color: #c9d1d9 !important; }
            h2, h3 { color: #8b949e !important; }
            h2 svg, h3 svg, .field svg { fill: #8b949e !important; }
            :root {
              --color-calendar-graph-day-bg: #161b22 !important;
              --color-calendar-graph-day-L1-bg: #333a42 !important;
              --color-calendar-graph-day-L2-bg: #4d5560 !important;
              --color-calendar-graph-day-L3-bg: #6e7681 !important;
              --color-calendar-graph-day-L4-bg: #c9d1d9 !important;
            }
